### ISSUE TITLE
Login with Mi Account

### ISSUE THREAD

**Issue by matteobaldelli** [markszabo/FlowerCareRegister#1]
I can't login with my Xiaomi Mi Account

**Comment by markszabo** [comment]
Hey, you need to use your Flower Care Account used to sign in to the [official Flower Care App](https://play.google.com/store/apps/details?id=com.huahuacaocao.flowercare).  Let me know if it works that way :)

**Comment by nivago** [comment]
Greetings! I'm entering the very same credentials I use for official FlowerCare app, and yet can't login. Error message in your app states "try to update your app". Somewhere on the net I've stumbled on info on new version of FlowerCare app - some update ago it've started to use some extra token/key for authorisation.

**Comment by markszabo** [comment]
Hi @nivago, thanks for letting me know, I'll take a look once I have the time

**Comment by markszabo** [comment]
Hi @nivago, I just released an update to Google Play addressing this new flow. Please take a look at let me know how it goes. Closing this issue now, feel free to reopen if the issue still persist.
